"""update selected_tables

Revision ID: 498a90e4ef00
Revises: 3acd19b21ac5
Create Date: 2023-07-09 22:05:57.869494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498a90e4ef00'
down_revision = '3acd19b21ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selected_subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(length=34), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selected_subject', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
