"""update selected_tables

Revision ID: 4fa474a295a8
Revises: 498a90e4ef00
Create Date: 2023-07-09 22:06:28.521115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fa474a295a8'
down_revision = '498a90e4ef00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selected_subject', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selected_subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', mysql.VARCHAR(length=34), nullable=True))

    # ### end Alembic commands ###
