"""Add selected_su 

Revision ID: a6e5b666ad3b
Revises: 
Create Date: 2023-07-03 22:17:46.293427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6e5b666ad3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selected_subject', schema=None) as batch_op:
        batch_op.alter_column('is_compulsory',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selected_subject', schema=None) as batch_op:
        batch_op.alter_column('is_compulsory',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###
