"""Update Answers table

Revision ID: d29b7ee4d168
Revises: 4c09667f75d4
Create Date: 2023-07-03 10:34:51.190422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd29b7ee4d168'
down_revision = '4c09667f75d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_column('new')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new', mysql.VARCHAR(length=23), nullable=True))

    # ### end Alembic commands ###
